// Generated by gencpp from file tutorial_2/SetBool.msg
// DO NOT EDIT!


#ifndef TUTORIAL_2_MESSAGE_SETBOOL_H
#define TUTORIAL_2_MESSAGE_SETBOOL_H

#include <ros/service_traits.h>


#include <tutorial_2/SetBoolRequest.h>
#include <tutorial_2/SetBoolResponse.h>


namespace tutorial_2
{

struct SetBool
{

typedef SetBoolRequest Request;
typedef SetBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetBool
} // namespace tutorial_2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tutorial_2::SetBool > {
  static const char* value()
  {
    return "09fb03525b03e7ea1fd3992bafd87e16";
  }

  static const char* value(const ::tutorial_2::SetBool&) { return value(); }
};

template<>
struct DataType< ::tutorial_2::SetBool > {
  static const char* value()
  {
    return "tutorial_2/SetBool";
  }

  static const char* value(const ::tutorial_2::SetBool&) { return value(); }
};


// service_traits::MD5Sum< ::tutorial_2::SetBoolRequest> should match
// service_traits::MD5Sum< ::tutorial_2::SetBool >
template<>
struct MD5Sum< ::tutorial_2::SetBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tutorial_2::SetBool >::value();
  }
  static const char* value(const ::tutorial_2::SetBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tutorial_2::SetBoolRequest> should match
// service_traits::DataType< ::tutorial_2::SetBool >
template<>
struct DataType< ::tutorial_2::SetBoolRequest>
{
  static const char* value()
  {
    return DataType< ::tutorial_2::SetBool >::value();
  }
  static const char* value(const ::tutorial_2::SetBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tutorial_2::SetBoolResponse> should match
// service_traits::MD5Sum< ::tutorial_2::SetBool >
template<>
struct MD5Sum< ::tutorial_2::SetBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tutorial_2::SetBool >::value();
  }
  static const char* value(const ::tutorial_2::SetBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tutorial_2::SetBoolResponse> should match
// service_traits::DataType< ::tutorial_2::SetBool >
template<>
struct DataType< ::tutorial_2::SetBoolResponse>
{
  static const char* value()
  {
    return DataType< ::tutorial_2::SetBool >::value();
  }
  static const char* value(const ::tutorial_2::SetBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUTORIAL_2_MESSAGE_SETBOOL_H
