#!/bin/bash

echo "Initializing ROS in raspi"
source devel/setup.bash
export ROS_MASTER_URI=http://<master-computer ip>:11311/
echo "ROS_MASTER_URI" $ROS_MASTER_URI
export ROS_IP=<computer ip>
echo "ROS_IP" $ROS_IP
export ROS_HOSTNAME=<computer ip>
echo "ROS_HOSTNAME" $ROS_HOSTNAME

